### ISSUE TITLE
3.2 and 3.3 not work on windows system

### ISSUE THREAD

**Issue by ELD400** [dimaryaz/jdmtool#18]
On windows, last your version make error on main on line 84 :
Python version 3.12.7, win10

with G1000 branch, all works on windows, not other branchs.

PS C:\temp> jdmtool read-database test.bin
Found device: Bus 001 Device 030: ID 0e39:1250
Traceback (most recent call last):
File "", line 198, in run_module_as_main
File "", line 88, in run_code
File "C:\Program Files\Python312\Scripts\jdmtool.exe_main.py", line 7, in
File "C:\Program Files\Python312\Lib\site-packages\jdmtool\main.py", line 1130, in main
func(**kwargs)
File "C:\Program Files\Python312\Lib\site-packages\jdmtool\main.py", line 84, in wrapper
handle.setAutoDetachKernelDriver(True)
File "C:\Program Files\Python312\Lib\site-packages\usb1_init.py", line 1217, in setAutoDetachKernelDriver
mayRaiseUSBError(libusb1.libusb_set_auto_detach_kernel_driver(
File "C:\Program Files\Python312\Lib\site-packages\usb1_init_.py", line 127, in mayRaiseUSBError
_raiseUSBError(value)
File "C:\Program Files\Python312\Lib\site-packages\usb1_init.py", line 119, in raiseUSBError
raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
usb1.USBErrorNotSupported: LIBUSB_ERROR_NOT_SUPPORTED [-12]

**Comment by dimaryaz** [comment]
Heh, I added the `setAutoDetachKernelDriver` call to try to fix an error on OS X - but it broke Windows. Looks like I just need to ignore that error. Should be easy.
