### ISSUE TITLE
Chartview, during transfer, Invalid dBase IV block on garmin_databases branch

### ISSUE THREAD

**Issue by ELD400** [dimaryaz/jdmtool#20]
Processing charts.ini...
Processing charts.bin: 100%|████████████████████████████████████████████████████████▉| 157M/157M [00:43<00:00, 3.60MB/s]
Guessing subscription for code 040ME10573...
Best match: 178352340, 600 airports
Processing charts.dbf...
Processing chrtlink.dbf...
Processing airports.dbf...
Processing notams.dbf + notams.dbt...
Traceback (most recent call last):
  File "/home/eld/.local/bin/jdmtool", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/eld/.local/share/pipx/venvs/jdmtool/lib/python3.12/site-packages/jdmtool/main.py", line 1013, in main
    func(**kwargs)
  File "/home/eld/.local/share/pipx/venvs/jdmtool/lib/python3.12/site-packages/jdmtool/main.py", line 697, in cmd_transfer
    _transfer_sd_card(services, pathlib.Path(device), vol_id)
  File "/home/eld/.local/share/pipx/venvs/jdmtool/lib/python3.12/site-packages/jdmtool/main.py", line 600, in _transfer_sd_card
    dot_jdm_config = transfer_func(service, path, volume_id)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eld/.local/share/pipx/venvs/jdmtool/lib/python3.12/site-packages/jdmtool/main.py", line 498, in _transfer_g1000_chartview
    cv.process_notams(ifr_airports, vfr_airports, ifr_countries, vfr_countries, charts_path)
  File "/home/eld/.local/share/pipx/venvs/jdmtool/lib/python3.12/site-packages/jdmtool/chartview.py", line 379, in process_notams
    memo = DbtFile.read_record(dbt_in, dbt_header, record[3])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eld/.local/share/pipx/venvs/jdmtool/lib/python3.12/site-packages/jdmtool/dbf.py", line 184, in read_record
    raise ValueError("Invalid dBase IV block")
ValueError: Invalid dBase IV block
D630:~$

**Comment by dimaryaz** [comment]
I see that you tried commenting it out in the code you posted in #19:

>            #if block_start[0:4] != cls.DBT4_BLOCK_START:
>            #    raise ValueError("Invalid dBase IV block")

Did that work?

Would you mind sending me your .zip from `~/.local/share/jdmtool/downloads/`, so I can try it myself? (You can upload it somewhere and send it to dima@gmail.com ; no need to post it here.)

**Comment by ELD400** [comment]
>Did that work?

It's just to go to end of compile, I can't tested now.

**Comment by dimaryaz** [comment]
Sorry for the delay.

> I have send zip file to you via link.

I've gone through my email, but cannot find it, not even in spam... Can you tell me the day you sent, some words in the email, etc.? Or send it again?

**Comment by dimaryaz** [comment]
Well, I reproduced it using data from another user...

I'm pretty sure this is actually a bug in Python's zipfile module, as crazy as that sounds. It works for me using Python 3.7 and 3.9, but crashes with Python 3.12.

In any case, I think I know how to work around it.
