### ISSUE TITLE
Fatal error while logging in

### ISSUE THREAD

**Issue by armellin** [dimaryaz/jdmtool#5]
Installed following README's instructions.

Doing "jdmtool login" I got:

Traceback (most recent call last):
  File "/home/armellin/.local/bin/jdmtool", line 8, in <module>
    sys.exit(main())
  File "/home/armellin/.local/lib/python3.8/site-packages/jdmtool/main.py", line 478, in main
    func(**kwargs)
  File "/home/armellin/.local/lib/python3.8/site-packages/jdmtool/main.py", line 88, in cmd_login
    downloader.login(username, password)
  File "/home/armellin/.local/lib/python3.8/site-packages/jdmtool/downloader.py", line 72, in login
    headers, params = self.get_common_headers_params()
  File "/home/armellin/.local/lib/python3.8/site-packages/jdmtool/downloader.py", line 50, in get_common_headers_params
    date_str, cov_check = cls.get_cov_check()
  File "/home/armellin/.local/lib/python3.8/site-packages/jdmtool/downloader.py", line 43, in get_cov_check
    now = datetime.datetime.now(datetime.UTC)
AttributeError: module 'datetime' has no attribute 'UTC'

**Comment by dimaryaz** [comment]
Ah, `datetime.UTC` was only added in Python 3.11. Let me fix that.

**Comment by dimaryaz** [comment]
Should be fixed now, in version 0.0.4.
